# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 876a62941d514150b0d409b796dfb954cef6024d69f725405e32f6b16b06625e091e3dad69deb908e5cbb2f5bc35a4627787a6fca6616cb3bb9f65bd87356920

test:
  secret_key_base: a5d270ec062c41bc78d864b1ca2f450a8e95456ca0eb3c9e3990dea3fa2fb953f094e3515f3e346bc5cb91d63788690526f14f53b903843d473bc91ee14462d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
